### ISSUE TITLE
 Support for multiple printers on a single AstroBox

### ISSUE THREAD

**Issue by KissmanCZ** [AstroPrint/AstroBox#125]
Please add feature request... many of us have multiple printers (i have 4 for now) and buying Rpi for every one printer is not good.solution. I understand that you need to sell your hardware, but this would be a perfect competitive advantage. Maybe you can make this as payable addon (pay per printer), why not... i will buy this addon even price will be same as the brand new AstroBox or Rpi, because I hate cables and I dont want Rpi farm in my home... from another side, be more green (eco) - why use 4 AC adapters when we can use only one.

Your web UI is perfectly prepared & designed for this...

**Comment by CoDanny** [comment]
This is no possible, not so much due to sales but more about complexity in the platforms. The Raspberry Pi won't be able to successfully handle multiple prints and the UI is simply not ready for it. 

This would be a completely different product which can be developed and attached to AstroPrint using the upcoming Server API but as fas as the AstroBox goes, we're not going to work on this any time soon.
