### ISSUE TITLE
New user lots of problems

### ISSUE THREAD

**Issue by Kenbigt** [AstroPrint/AstroBox#169]
Been using Octoprint for ages and seen this software installed and nothing working
Using Raspberry pi v3 WiFi not creating hotspot to connect and setup connected using Ethernet cable
Z axis manual movement not working on webpage but x and y axis is
uploaded 3 stl files only one appeared back for about 4 seconds ready to print then is no where to
be seen dont know where it has gone i know you are releasing a updated build can you advise on a time scale as i really like the look of your software i thing you guys do a marvelous job.

I am running a CTC 3D Printer Salfish firmware.

Thanks
Kenneth

**Comment by CoDanny** [comment]
@Kenbigt the Z axis problem is already known ( #166 ). The slice one needs more details.

When opening an issues, please report one problem per issue as otherwise it's difficult to track. If you have general problems or need help it's best to contact us via our support system at https://astroprint.zendesk.com or visit our forum https://forum.astroprint.com/

I'll close this issue.
