### ISSUE TITLE
Add ability to specify Astrobox IP:port or domain:port

### ISSUE THREAD

**Issue by macdarren** [AstroPrint/AstroBox#237]
add a setup in the Astroprint web configuration to specify the Astrobox IP or domain with an optional port number this would allow connecting to the Astrobox directly from the web interface even when not on the same local network.  Obviously some user configuration would be required at the router etc, so this is an advanced feature.

**Comment by CoDanny** [comment]
This can be done by going into the file `/etc/astrobox/config.yaml` and adding the following lines:

```
server:
  host: 192.168.0.1 
  port: 8080
```

If the `server` section is already in your config.yaml, just add the lines below. Indentation is important (2 spaces)

Since this seems pretty advanced, we will leave it as is. Adding it to the settings UI will most likely confuse some people.
