### ISSUE TITLE
Time estimates with support

### ISSUE THREAD

**Issue by tescalada** [AstroPrint/AstroBox#249]
Using supports seems to throw off the time estimates. I haven't calculated it or done extensive testing, but it seems like some "12 hour" prints end up taking more like 16 hours with supports.

**Comment by CoDanny** [comment]
Variations are expected due to HW not always moving as fast as instructed. Out estimates are based on the GCODE commands speed settings. I would think the one thing that affects estimates most of long extrusion moves.

This is hard to get right as the variance really depends on the HW your printer uses.
